test_that("rdlearn and plot", {
  data(acces)
  library(nprobust)
  library(nnet)
  library(ggplot2)
  library(dplyr)
  library(glue)
  library(purrr)
  library(tidyr)
  result <- rdlearn(y = "elig", x = "saber11", c = "cutoff", data = acces, fold = 5, M = c(0, 1), cost = 0)
  result <- rdlearn(y = "elig", x = "saber11", c = "cutoff", data = acces, fold = 10, M = c(0, 1), cost = 0)
  result <- rdlearn(y = "elig", x = "saber11", c = "cutoff", data = acces, fold = 20, M = c(0, 1), cost = 0)
  plot(result)
})
